export const USER_POST_SUCCESS="USER_POST_SUCCESS";
export const USER_POST_REQUEST="USER_POST_REQUEST";
export const USER_POST_FAIL="USER_POST_FAIL";
export const USER_POST_RESET="USER_POST_RESET";

export const POST_LIST_REQUEST ="POST_LIST_REQUEST"
export const POST_LIST_SUCCESS='POST_LIST_SUCCESS'
export const POST_LIST_FAIL='POST_LIST_FAIL'
export const POST_LIST_RESET='POST_LIST_RESET'

export const QUESTION_LIST_REQUEST ="QUESTION_LIST_REQUEST"
export const QUESTION_LIST_SUCCESS='QUESTION_LIST_SUCCESS'
export const QUESTION_LIST_FAIL='QUESTION_LIST_FAIL'
export const QUESTION_LIST_RESET='QUESTION_LIST_RESET'

export const POST_DETAIL_REQUEST ="POST_DETAIL_REQUEST"
export const POST_DETAIL_sUCCESS ="POST_DETAIL_SUCCESS"
export const POST_DETAIL_FAIL ="POST_DETAIL_FAIL"
export const POST_DETAIL_RESET ="POST_DETAIL_RESET"

export const POST_BY_USER_REQUEST= "POST_BY_USER_REQUEST"
export const POST_BY_USER_SUCCESS= "POST_BY_USER_SUCCESS"
export const POST_BY_USER_FAIL= "POST_BY_USER_FAIL"
export const POST_BY_USER_RESET= "POST_BY_USER_RESET"

export const USER_DELETE_POST_REQUEST = "USER_DELETE_POST_REQUEST"
export const USER_DELETE_POST_SUCCESS = "USER_DELETE_POST_SUCCESS"
export const USER_DELETE_POST_FAIL = "USER_DELETE_POST_FAIL"
export const USER_DELETE_POST_RESET = "USER_DELETE_POST_RESET"

export const GET_COMMENT_REQUEST ="GET_COMMENT_REQUEST"
export const GET_COMMENT_SUCCESS ="GET_COMMENT_SUCCESS"
export const GET_COMMENT_FAIL = "GET_COMMENT_FAIL"
export const GET_COMMENT_RESET = "GET_COMMENT_RESET"

export const ADD_COMMENT_REQUEST ="ADD_COMMENT_REQUEST"
export const ADD_COMMENT_SUCCESS ="ADD_COMMENT_SUCCESS"
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL"
export const ADD_COMMENT_RESET = "ADD_COMMENT_RESET"

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST"
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS"
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL"
export const DELETE_COMMENT_RESET = "DELETE_COMMENT_RESET"

export const GET_POST_BY_TAG_REQUEST ="GET_POST_BY_TAG_REQUEST"
export const GET_POST_BY_TAG_SUCCESS ="GET_POST_BY_TAG_SUCCESS"
export const GET_POST_BY_TAG_FAIL = "GET_POST_BY_TAG_FAIL"
export const GET_POST_BY_TAG_RESET = "GET_POST_BY_TAG_RESET"

export const UPDATE_VIEW_REQUEST ="UPDATE_VIEW_REQUEST"
export const UPDATE_VIEW_SUCCESS ="UPDATE_VIEW_SUCCESS"
export const UPDATE_VIEW_FAIL = "UPDATE_VIEW_FAIL"
export const UPDATE_VIEW_RESET = "UPDATE_VIEW_RESET"

export const UPDATE_CMT_REQUEST ="UPDATE_CMT_REQUEST"
export const UPDATE_CMT_SUCCESS ="UPDATE_CMT_SUCCESS"
export const UPDATE_CMT_FAIL = "UPDATE_CMT_FAIL"
export const UPDATE_CMT_RESET = "UPDATE_CMT_RESET"

export const SEARCH_POST_REQUEST ="SEARCH_POST_REQUEST"
export const SEARCH_POST_SUCCESS ="SEARCH_POST_SUCCESS"
export const SEARCH_POST_FAIL = "SEARCH_POST_FAIL"
export const SEARCH_POST_RESET = "SEARCH_POST_RESET"